Added the fundamental spaces
FluxML/Gym.jl pull request #7
Opened 2019-03-29 09:43 UTC by kraftpunk97

seed and copy functions still need to be implemented. Modified CartPole.jl (CartPole-v1.1.jl) to run on these spaces.

2019-03-30 13:30 UTC, tejank10 requested changes
Thanks @kraftpunk97 for great work!

2019-03-30 13:30 UTC, tejank10 commented on src/Spaces/discrete.jl
> +sample(self::Discrete) = rand(1:self.n)
`self` -> `d` (or anything else which would imply that given object is a `Discrete` when read)

2019-03-30 13:30 UTC, tejank10 commented on src/Spaces/discrete.jl
> +    end
Clever use of try catch!

2019-03-30 13:30 UTC, tejank10 commented on src/Spaces/multi-binary.jl
> +contains(self::MultiBinary, x) = all(boolor.(x .== 0, x .== 1))
Any particular reason for introducing `boolor`? Can we do `all(x .== 0 .| x .== 1)`?

2019-03-30 13:30 UTC, tejank10 commented on src/Spaces/multi-binary.jl
> +Base.:(==)(self::MultiBinary, other::MultiBinary) = return self.n == other.n
`return` can be dropped here

2019-03-31 05:09 UTC, kraftpunk97 commented on src/Spaces/discrete.jl
> +sample(self::Discrete) = rand(1:self.n)
A little confused here. Are you suggesting something like `sample(discrete_obj::Discrete) = rand(1:discrete_obj.n)`?

2019-03-31 05:10 UTC, kraftpunk97 commented on src/Spaces/discrete.jl
> +    end
👌👍

2019-03-31 05:44 UTC, kraftpunk97 commented on src/Spaces/multi-binary.jl
> +contains(self::MultiBinary, x) = all(boolor.(x .== 0, x .== 1))
Sorry for that, I was just testing something and I forgot to remove that function. Consider it fixed...

2019-04-02 00:04 UTC, kraftpunk97 commented
@tejank10 Made changes as requested. Please review and verify.

2019-04-02 14:02 UTC, tejank10 commented on src/Spaces/discrete.jl
> +sample(self::Discrete) = rand(1:self.n)
Yeah, something like that.

2019-04-04 13:30 UTC, tejank10 approved these changes

2019-04-06 10:43 UTC, kraftpunk97 commented
If the changes are approved then please merge. Thanks.

2019-04-06 15:38 UTC, tejank10 commented
Great! I intend to replace CartPole with CartPole1.1, if the examples in [model-zoo](https://github.com/FluxML/model-zoo/tree/master/games/differentiable-programming/cartpole) is not breaking.

2019-04-07 06:08 UTC, kraftpunk97 commented
Made the necessary changes. Please verify.

2019-04-07 14:41 UTC, merged

2019-04-07 14:42 UTC, tejank10 commented
Great work @kraftpunk97 , Thanks!

2019-04-07 14:55 UTC, kraftpunk97 commented
I have never experienced joy like this before. Thanks for sticking it out with me.